## Bài 3.1

In [4]:
import numpy as np
print("Phiên bản Numpy hiện tại:", np.__version__)
print("Cấu hình xây dựng của Numpy:")
np.show_config()

Phiên bản Numpy hiện tại: 2.3.4
Cấu hình xây dựng của Numpy:
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-0fv2o5t8/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-0fv2o5t8/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.30  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.30
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-0fv2o5t8/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-0fv2o5t8/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64

## Bài 3.2

In [5]:
import numpy as np

arr = np.arange(10)
print("Mảng arr:", arr)
print("Kiểu dữ liệu của arr:", arr.dtype)
print("Kích thước của arr:", arr.shape)

arr_odd = arr[arr % 2 == 1]
arr_even = arr[arr % 2 == 0]
print("Các phần tử lẻ:", arr_odd)
print("Các phần tử chẵn:", arr_even)

arr_update_1 = arr.copy()
arr_update_1[arr_update_1 % 2 == 1] = 100
print("Mảng sau khi cập nhật (arr_update_1):", arr_update_1)

Mảng arr: [0 1 2 3 4 5 6 7 8 9]
Kiểu dữ liệu của arr: int64
Kích thước của arr: (10,)
Các phần tử lẻ: [1 3 5 7 9]
Các phần tử chẵn: [0 2 4 6 8]
Mảng sau khi cập nhật (arr_update_1): [  0 100   2 100   4 100   6 100   8 100]


## Bài 3.3


In [6]:
import numpy as np

arr_a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
arr_b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

print("arr_a:", arr_a)
print("arr_b:", arr_b)

arr_c = np.intersect1d(arr_a, arr_b)
print("arr_c (phần tử xuất hiện ở cả hai mảng):", arr_c)

arr_d = np.setdiff1d(arr_a, arr_b)
print("arr_d (phần tử chỉ có trong arr_a):", arr_d)

arr_e = np.array([2, 6, 1, 9, 10, 3, 27, 8, 6, 25, 16])

arr_f = arr_e[(arr_e >= 5) & (arr_e <= 10)]
print("arr_e:", arr_e)
print("arr_f (phần tử từ 5 đến 10):", arr_f)

arr_a: [1 2 3 2 3 4 3 4 5 6]
arr_b: [ 7  2 10  2  7  4  9  4  9  8]
arr_c (phần tử xuất hiện ở cả hai mảng): [2 4]
arr_d (phần tử chỉ có trong arr_a): [1 3 5 6]
arr_e: [ 2  6  1  9 10  3 27  8  6 25 16]
arr_f (phần tử từ 5 đến 10): [ 6  9 10  8  6]


## Bài 3.4

In [1]:
import numpy as np

arr_zeros = np.zeros(10, dtype=int)
print(f"arr_zeros ban đầu:\n{arr_zeros}")

arr_zeros[4] = 1
print(f"arr_zeros sau khi cập nhật:\n{arr_zeros}")
print("-" * 20)

arr_h = np.arange(10, 25)
print(f"arr_h:\n{arr_h}")

arr_h_reversed = arr_h[::-1]
print(f"arr_h đảo ngược:\n{arr_h_reversed}")
print("-" * 20)

arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0])
print(f"arr_k:\n{arr_k}")

arr_l = arr_k[arr_k != 0]
print(f"arr_l (các phần tử khác 0 của arr_k):\n{arr_l}")
print("-" * 20)

arr_l = np.append(arr_l, [10, 20])
print(f"arr_l sau khi thêm 10 và 20:\n{arr_l}")
print("-" * 20)

arr_l = np.insert(arr_l, 5, 100)
print(f"arr_l sau khi thêm 100 vào index 5:\n{arr_l}")
print("-" * 20)

arr_l = np.delete(arr_l, [1, 2])
print(f"arr_l sau khi xóa phần tử ở index 1 và 2:\n{arr_l}")
print("-" * 20)

arr_zeros ban đầu:
[0 0 0 0 0 0 0 0 0 0]
arr_zeros sau khi cập nhật:
[0 0 0 0 1 0 0 0 0 0]
--------------------
arr_h:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
arr_h đảo ngược:
[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
--------------------
arr_k:
[1 2 0 8 2 0 1 3 0 5 0]
arr_l (các phần tử khác 0 của arr_k):
[1 2 8 2 1 3 5]
--------------------
arr_l sau khi thêm 10 và 20:
[ 1  2  8  2  1  3  5 10 20]
--------------------
arr_l sau khi thêm 100 vào index 5:
[  1   2   8   2   1 100   3   5  10  20]
--------------------
arr_l sau khi xóa phần tử ở index 1 và 2:
[  1   2   1 100   3   5  10  20]
--------------------


## Bài 3.6

In [15]:
import numpy as np

arr_true = np.full((3, 3), True)
print(f"arr_true:\n{arr_true}")
print("-" * 40)

arr_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

arr_2D = arr_1D.reshape((3, 3))
print(f"arr_2D ban đầu:\n{arr_2D}")

arr_2D = arr_2D[:, [2, 1, 0]]
print(f"arr_2D sau khi hoán đổi cột 1 và 3:\n{arr_2D}")
print("-" * 40)


arr_2D = arr_2D[[1, 0, 2], :]
print(f"arr_2D sau khi hoán đổi dòng 1 và 2:\n{arr_2D}")
print("-" * 40)



arr_2D_reversed_rows = arr_2D[::-1, :]
print(f"arr_2D sau khi đảo ngược các dòng:\n{arr_2D_reversed_rows}")
arr_2D = arr_2D_reversed_rows 
print("-" * 40)


arr_2D_reversed_cols = arr_2D[:, ::-1]
print(f"arr_2D sau khi đảo ngược các cột:\n{arr_2D_reversed_cols}")
print("-" * 40)

arr_2D_null = np.array([[1, 2, 3], [np.nan, 5, 6], [7, np.nan, 9], [4, 5, 6]])
print(f"arr_2D_null:\n{arr_2D_null}")

has_null = np.isnan(arr_2D_null).any()

print(f"Trong arr_2D_null có giá trị rỗng (NaN) không? **{has_null}**")
print("-" * 40)

arr_2D_null[np.isnan(arr_2D_null)] = 0

print(f"arr_2D_null sau khi thay thế NaN bằng 0:\n{arr_2D_null}")
print("-" * 40)

arr_true:
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
----------------------------------------
arr_2D ban đầu:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
arr_2D sau khi hoán đổi cột 1 và 3:
[[2 1 0]
 [5 4 3]
 [8 7 6]]
----------------------------------------
arr_2D sau khi hoán đổi dòng 1 và 2:
[[5 4 3]
 [2 1 0]
 [8 7 6]]
----------------------------------------
arr_2D sau khi đảo ngược các dòng:
[[8 7 6]
 [2 1 0]
 [5 4 3]]
----------------------------------------
arr_2D sau khi đảo ngược các cột:
[[6 7 8]
 [0 1 2]
 [3 4 5]]
----------------------------------------
arr_2D_null:
[[ 1.  2.  3.]
 [nan  5.  6.]
 [ 7. nan  9.]
 [ 4.  5.  6.]]
Trong arr_2D_null có giá trị rỗng (NaN) không? **True**
----------------------------------------
arr_2D_null sau khi thay thế NaN bằng 0:
[[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]
----------------------------------------


## Bài 3.7

In [25]:

data = """74 180
72 215
73 210
75 205
78 210
69 185
71 190
76 200
77 230
70 195
73 220
74 205
72 190
79 240
68 175
77 225
75 200
74 210
76 215
78 220
73 205
70 185
69 180
71 195
75 210
77 225
78 230
74 200
72 190
70 185
68 170
73 200
76 215
78 220
74 205
71 195
70 190
75 210
77 230
79 240"""

lines = data.strip().split("\n")

while len(lines) < 150:
    lines.extend(lines) 


lines = lines[:150]


with open("baseball_2D.txt", "w") as f:
    f.write("\n".join(lines))

print(" Đã tạo file baseball_2D.txt.")

 Đã tạo file baseball_2D.txt.


In [ ]:
import numpy as np

baseball = []
with open("baseball_2D.txt", "r") as f:
    for line in f:
        values = line.strip().split()
        baseball.append([float(values[0]), float(values[1])])

np_baseball = np.array(baseball)

print("Kiểu dữ liệu của np_baseball:", np_baseball.dtype)
print("Kích thước của np_baseball:", np_baseball.shape)

print("Dòng thứ 50 trong np_baseball:", np_baseball[49])

np_weight = np_baseball[:, 1]
print("Mảng cân nặng:", np_weight)

height_124 = np_baseball[123, 0]
print("Chiều cao của vận động viên thứ 124:", height_124)

avg_height = np.mean(np_baseball[:, 0])
avg_weight = np.mean(np_baseball[:, 1])
print("Chiều cao trung bình:", avg_height)
print("Cân nặng trung bình:", avg_weight)

correlation = np.corrcoef(np_baseball[:, 0], np_baseball[:, 1])[0, 1]
print("Hệ số tương quan giữa chiều cao và cân nặng:", correlation)

if correlation > 0:
    print("→ Có tương quan thuận: cầu thủ cao hơn thường nặng hơn.")
elif correlation < 0:
    print("→ Có tương quan nghịch: cầu thủ cao hơn thường nhẹ hơn.")
else:
    print("→ Không có tương quan rõ ràng giữa chiều cao và cân nặng.")

Kiểu dữ liệu của np_baseball: float64
Kích thước của np_baseball: (150, 2)
Dòng thứ 50 trong np_baseball: [ 70. 195.]
Mảng cân nặng: [180. 215. 210. 205. 210. 185. 190. 200. 230. 195. 220. 205. 190. 240.
 175. 225. 200. 210. 215. 220. 205. 185. 180. 195. 210. 225. 230. 200.
 190. 185. 170. 200. 215. 220. 205. 195. 190. 210. 230. 240. 180. 215.
 210. 205. 210. 185. 190. 200. 230. 195. 220. 205. 190. 240. 175. 225.
 200. 210. 215. 220. 205. 185. 180. 195. 210. 225. 230. 200. 190. 185.
 170. 200. 215. 220. 205. 195. 190. 210. 230. 240. 180. 215. 210. 205.
 210. 185. 190. 200. 230. 195. 220. 205. 190. 240. 175. 225. 200. 210.
 215. 220. 205. 185. 180. 195. 210. 225. 230. 200. 190. 185. 170. 200.
 215. 220. 205. 195. 190. 210. 230. 240. 180. 215. 210. 205. 210. 185.
 190. 200. 230. 195. 220. 205. 190. 240. 175. 225. 200. 210. 215. 220.
 205. 185. 180. 195. 210. 225. 230. 200. 190. 185.]
Chiều cao của vận động viên thứ 124: 75.0
Chiều cao trung bình: 73.75333333333333
Cân nặng trung bình: 20

## Bài 3.8

In [21]:

heights_data = [
    180, 175, 190, 178, 185, 170, 182, 188, 176, 192,
    181, 174, 187, 179, 183, 186, 177, 189, 172, 184
]

positions_data = [
    "GK", "D", "M", "A", "GK", "D", "M", "A", "D", "A",
    "M", "GK", "A", "D", "M", "GK", "A", "D", "M", "A"
]

with open("heights.txt", "w") as f:
    for h in heights_data:
        f.write(str(h) + "\n")

with open("positions.txt", "w") as f:
    for p in positions_data:
        f.write(p + "\n")

print(" Đã tạo xong 2 tập tin heights.txt và positions.txt")

 Đã tạo xong 2 tập tin heights.txt và positions.txt


In [22]:
import numpy as np

with open("heights.txt") as f:
    heights = [float(line.strip()) for line in f]

with open("positions.txt") as f:
    positions = [line.strip() for line in f]

np_positions = np.array(positions)
np_heights = np.array(heights)

print("Kiểu dữ liệu np_positions:", np_positions.dtype)
print("Kiểu dữ liệu np_heights:", np_heights.dtype)

mean_GK = np.mean(np_heights[np_positions == "GK"])
print("Chiều cao trung bình của GK:", round(mean_GK, 2))

mean_not_GK = np.mean(np_heights[np_positions != "GK"])
print("Chiều cao trung bình của các vị trí khác GK:", round(mean_not_GK, 2))

players = np.array(list(zip(np_positions, np_heights)),
                   dtype=[('position', 'U5'), ('height', 'float')])

players_sorted = np.sort(players, order='height')
print("Chiều cao thấp nhất:", players_sorted[0])
print("Chiều cao cao nhất:", players_sorted[-1])

Kiểu dữ liệu np_positions: <U2
Kiểu dữ liệu np_heights: float64
Chiều cao trung bình của GK: 181.25
Chiều cao trung bình của các vị trí khác GK: 181.44
Chiều cao thấp nhất: ('D', 170.0)
Chiều cao cao nhất: ('A', 192.0)


## Bài 3.9

In [26]:
import pandas as pd

data = {
    'Team': ['Germany', 'France', 'England', 'Italy', 'Spain', 'Portugal', 'Russia', 'Greece'],
    'Goals': [10, 3, 5, 6, 12, 7, 5, 4],
    'Yellow Cards': [4, 6, 5, 16, 11, 7, 9, 12],
    'Red Cards': [0, 0, 0, 1, 0, 1, 0, 1],
    'Shooting Accuracy': ['56%', '45%', '50%', '48%', '60%', '53%', '42%', '38%']
}

df = pd.DataFrame(data)

df.to_csv('euro2012.csv', index=False)

print(" File euro2012.csv đã được tạo")

 File euro2012.csv đã được tạo


In [27]:
import pandas as pd

euro12 = pd.read_csv('euro2012.csv')

print("Kiểu dữ liệu:", type(euro12))
print("Kích thước (shape):", euro12.shape)
print("Các cột:", euro12.columns.tolist())

print("\nCột Goals:")
print(euro12['Goals'])

print("\nSố đội tham gia Euro 2012:", euro12['Team'].count())

print("\nThông tin chi tiết Euro2012:")
print(euro12.info())

discipline = euro12[['Team', 'Yellow Cards', 'Red Cards']]
print("\nDataFrame discipline:")
print(discipline)

discipline_sorted = discipline.sort_values(by=['Red Cards', 'Yellow Cards'], ascending=[False, False])
print("\nSau khi sắp xếp:")
print(discipline_sorted)

print("\nTrung bình Yellow Cards:", round(discipline['Yellow Cards'].mean(), 2))

print("\nCác đội ghi hơn 6 bàn:")
print(euro12[euro12['Goals'] > 6])

print("\nCác đội bắt đầu bằng chữ 'G':")
print(euro12[euro12['Team'].str.startswith('G')])

print("\n7 cột đầu:")
print(euro12.iloc[:, :7])

print("\nTất cả trừ 3 cột cuối:")
print(euro12.iloc[:, :-3])

print("\nMột số cột được chọn:")
print(euro12[['Team', 'Goals', 'Shooting Accuracy', 'Yellow Cards', 'Red Cards']])

print("\nChỉ hiện 'Team' và 'Shooting Accuracy' cho England, Italy, Russia:")
print(euro12.loc[euro12['Team'].isin(['England', 'Italy', 'Russia']), ['Team', 'Shooting Accuracy']])

Kiểu dữ liệu: <class 'pandas.core.frame.DataFrame'>
Kích thước (shape): (8, 5)
Các cột: ['Team', 'Goals', 'Yellow Cards', 'Red Cards', 'Shooting Accuracy']

Cột Goals:
0    10
1     3
2     5
3     6
4    12
5     7
6     5
7     4
Name: Goals, dtype: int64

Số đội tham gia Euro 2012: 8

Thông tin chi tiết Euro2012:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Team               8 non-null      object
 1   Goals              8 non-null      int64 
 2   Yellow Cards       8 non-null      int64 
 3   Red Cards          8 non-null      int64 
 4   Shooting Accuracy  8 non-null      object
dtypes: int64(3), object(2)
memory usage: 452.0+ bytes
None

DataFrame discipline:
       Team  Yellow Cards  Red Cards
0   Germany             4          0
1    France             6          0
2   England             5          0
3     Italy           

## Bài 3.10


In [28]:
import pandas as pd

data = {
    'country': ['USA', 'France', 'Germany', 'Italy', 'Spain', 'UK', 'China', 'India', 'Brazil', 'Australia'],
    'continent': ['North America', 'Europe', 'Europe', 'Europe', 'Europe', 'Europe', 'Asia', 'Asia', 'South America', 'Oceania'],
    'beer_servings': [229, 127, 346, 85, 193, 245, 40, 18, 245, 261],
    'spirit_servings': [87, 99, 175, 123, 101, 89, 40, 15, 90, 72],
    'wine_servings': [50, 312, 175, 218, 250, 101, 35, 12, 20, 85],
    'total_litres_of_pure_alcohol': [9.8, 12.3, 11.5, 12.9, 12.1, 11.7, 5.1, 4.3, 7.0, 10.0]
}

df = pd.DataFrame(data)

df.to_csv('drinks.csv', index=False)

print("File drinks.csv đã được tạo.")

File drinks.csv đã được tạo.


In [29]:

drink = pd.read_csv('drinks.csv', index_col=0)


print("Kiểu dữ liệu:", type(drink))
print("Kích thước (shape):", drink.shape)

print("Các cột:", drink.columns.tolist())

print("\n5 dòng đầu (head):\n", drink.head())
print("\n5 dòng cuối (tail):\n", drink.tail())

mean_beer = drink.groupby('continent')['beer_servings'].mean()
print("\nSố lượng bia tiêu thụ trung bình theo châu lục:\n", mean_beer)

wine_stats = drink.groupby('continent')['wine_servings'].describe()
print("\nThông tin thống kê rượu vang theo châu lục:\n", wine_stats)

mean_drinks = drink.groupby('continent')[['beer_servings','wine_servings','spirit_servings']].mean()
print("\nTrung bình bia, rượu vang, rượu mạnh theo châu lục:\n", mean_drinks)

median_drinks = drink.groupby('continent')[['beer_servings','wine_servings','spirit_servings']].median()
print("\nTrung vị bia, rượu vang, rượu mạnh theo châu lục:\n", median_drinks)

spirit_stats = drink.groupby('continent')['spirit_servings'].agg(['mean','max','min'])
print("\nSpirit servings - mean, max, min theo châu lục:\n", spirit_stats)
sorted_beer = drink.sort_values(by='beer_servings', ascending=True)

print("\n5 quốc gia tiêu thụ bia nhiều nhất:\n", sorted_beer.tail(5))
print("\n5 quốc gia tiêu thụ bia ít nhất:\n", sorted_beer.head(5))

Kiểu dữ liệu: <class 'pandas.core.frame.DataFrame'>
Kích thước (shape): (10, 5)
Các cột: ['continent', 'beer_servings', 'spirit_servings', 'wine_servings', 'total_litres_of_pure_alcohol']

5 dòng đầu (head):
              continent  beer_servings  spirit_servings  wine_servings  \
country                                                                 
USA      North America            229               87             50   
France          Europe            127               99            312   
Germany         Europe            346              175            175   
Italy           Europe             85              123            218   
Spain           Europe            193              101            250   

         total_litres_of_pure_alcohol  
country                                
USA                               9.8  
France                           12.3  
Germany                          11.5  
Italy                            12.9  
Spain                            12.1  

## Bài 3.11

In [30]:
import pandas as pd

# Tạo stocks1.csv
stocks1_data = {
    'date': ['2025-01-01','2025-01-02','2025-01-03','2025-01-04','2025-01-05'],
    'symbol': ['AAPL','AAPL','GOOG','GOOG','MSFT'],
    'open': [150, 152, 1200, 1195, 210],
    'high': [151, None, 1205, 1200, 215],  # có giá trị None để test Null
    'low': [149, 151, None, 1185, 208],    # có giá trị None để test Null
    'close': [150.5, 151.5, 1202, 1198, 212],
    'volume': [10000, 12000, 5000, 6000, 8000]
}
pd.DataFrame(stocks1_data).to_csv('stocks1.csv', index=False)

# Tạo stocks2.csv
stocks2_data = {
    'date': ['2025-01-01','2025-01-02','2025-01-03','2025-01-04','2025-01-05'],
    'symbol': ['FB','FB','TSLA','TSLA','AMZN'],
    'open': [270, 272, 650, 655, 3100],
    'high': [275, 274, 655, 660, 3120],
    'low': [268, 269, 645, 650, 3090],
    'close': [272, 273, 652, 658, 3110],
    'volume': [7000, 8000, 4000, 4500, 9000]
}
pd.DataFrame(stocks2_data).to_csv('stocks2.csv', index=False)

# Tạo companies.csv
companies_data = {
    'name': ['AAPL','GOOG','MSFT','FB','TSLA','AMZN'],
    'employees': [150000, 135000, 163000, 58000, 70000, 133000],
    'headquarters_city': ['Cupertino','Mountain View','Redmond','Menlo Park','Palo Alto','Seattle'],
    'headquarters_state': ['CA','CA','WA','CA','CA','WA']
}
pd.DataFrame(companies_data).to_csv('companies.csv', index=False)

print("Đã tạo xong các file CSV: stocks1.csv, stocks2.csv, companies.csv")

Đã tạo xong các file CSV: stocks1.csv, stocks2.csv, companies.csv


In [31]:
# 1a) 
stocks1 = pd.read_csv('stocks1.csv')
print("stocks1 - 5 dòng đầu:\n", stocks1.head())
print("stocks1 - 5 dòng cuối:\n", stocks1.tail())
print("stocks1 dtypes:\n", stocks1.dtypes)
print("stocks1 info:")
stocks1.info()

# 1b) 
stocks2 = pd.read_csv('stocks2.csv')
print("\nstocks2 - 5 dòng đầu:\n", stocks2.head())
print("stocks2 - 5 dòng cuối:\n", stocks2.tail())
print("stocks2 dtypes:\n", stocks2.dtypes)
print("stocks2 info:")
stocks2.info()

# 1c)
companies = pd.read_csv('companies.csv')
print("\ncompanies data:\n", companies)
print("companies dtypes:\n", companies.dtypes)
print("companies info:")
companies.info()

#
print("\nNull values in stocks1:\n", stocks1.isnull().sum())
stocks1['high'] = stocks1.groupby('symbol')['high'].transform(lambda x: x.fillna(x.max()))
stocks1['low'] = stocks1.groupby('symbol')['low'].transform(lambda x: x.fillna(x.min()))
print("\nSau khi thay thế Null:\n", stocks1)

stocks = pd.concat([stocks1, stocks2], ignore_index=True)
print("\n15 dòng cuối của stocks:\n", stocks.tail(15))

stocks_companies = pd.merge(stocks, companies, left_on='symbol', right_on='name', how='left')
print("\n5 dòng đầu stocks_companies:\n", stocks_companies.head())

mean_values = stocks_companies.groupby('symbol')[['open','high','low','close','volume']].mean()
print("\nGiá trung bình và volume trung bình mỗi công ty:\n", mean_values)

close_stats = stocks_companies.groupby('symbol')['close'].agg(['mean','max','min'])
print("\nClose price - mean, max, min mỗi công ty:\n", close_stats)

stocks_companies['parsed_time'] = pd.to_datetime(stocks_companies['date'])
print("\nKiểu dữ liệu của parsed_time:", stocks_companies['parsed_time'].dtype)
print("5 dòng đầu:\n", stocks_companies[['date','parsed_time']].head())

stocks_companies['result'] = stocks_companies.apply(lambda row: 'up' if row['close'] > row['open'] else 'down', axis=1)
print("\n5 dòng đầu với cột result:\n", stocks_companies[['symbol','open','close','result']].head())

stocks1 - 5 dòng đầu:
          date symbol  open    high     low   close  volume
0  2025-01-01   AAPL   150   151.0   149.0   150.5   10000
1  2025-01-02   AAPL   152     NaN   151.0   151.5   12000
2  2025-01-03   GOOG  1200  1205.0     NaN  1202.0    5000
3  2025-01-04   GOOG  1195  1200.0  1185.0  1198.0    6000
4  2025-01-05   MSFT   210   215.0   208.0   212.0    8000
stocks1 - 5 dòng cuối:
          date symbol  open    high     low   close  volume
0  2025-01-01   AAPL   150   151.0   149.0   150.5   10000
1  2025-01-02   AAPL   152     NaN   151.0   151.5   12000
2  2025-01-03   GOOG  1200  1205.0     NaN  1202.0    5000
3  2025-01-04   GOOG  1195  1200.0  1185.0  1198.0    6000
4  2025-01-05   MSFT   210   215.0   208.0   212.0    8000
stocks1 dtypes:
 date       object
symbol     object
open        int64
high      float64
low       float64
close     float64
volume      int64
dtype: object
stocks1 info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data c

## Bài 3.12

In [33]:
import os
import urllib.request
import zipfile

# 1. Xác định URL và nơi lưu trữ
url = "https://grouplens.org/datasets/movielens/latest/"  # đường dẫn tải chính thức  [oai_citation:0‡GroupLens](https://grouplens.org/datasets/movielens/latest/?utm_source=chatgpt.com)
download_path = "ml-latest-small.zip"
extract_dir = "ml-latest-small"

# 2. Nếu file chưa tồn tại thì tải về
if not os.path.exists(download_path):
    print("Đang tải dữ liệu từ:", url)
    urllib.request.urlretrieve(url, download_path)
    print("Tải xong:", download_path)
else:
    print("File đã tồn tại:", download_path)

# 3. Giải nén nếu thư mục chứa dữ liệu chưa được tạo
if not os.path.exists(extract_dir):
    print("Đang giải nén vào thư mục:", extract_dir)
    with zipfile.ZipFile(download_path, 'r') as zip_ref:
        zip_ref.extractall(extract_dir)
    print("Giải nén xong.")
else:
    print("Thư mục đã tồn tại:", extract_dir)

# 4. Xác nhận các file chính
print("Các file trong thư mục:", os.listdir(extract_dir))

File đã tồn tại: ml-latest-small.zip
Thư mục đã tồn tại: ml-latest-small
Các file trong thư mục: ['ml-latest-small']


In [ ]:
# Đọc dữ liệu
movies_df = pd.read_csv('movies.csv')
ratings_df = pd.read_csv('ratings.csv')

# Kiểm tra dữ liệu
print("Movies DataFrame:")
print(movies_df.head())
print("\nRatings DataFrame:")
print(ratings_df.head())

print("\nMovies info:")
movies_df.info()
print("\nRatings info:")
ratings_df.info()

print("\nMissing values in movies:", movies_df.isnull().sum())
print("Missing values in ratings:", ratings_df.isnull().sum())

movies_df.dropna(inplace=True)
ratings_df.dropna(inplace=True)

movies_ratings = pd.merge(ratings_df, movies_df, on='movieId', how='left')
print("\n5 dòng đầu sau khi gộp:")
print(movies_ratings.head())

high_rated = movies_ratings[movies_ratings['rating'] >= 4.0]
print("\nMovies with rating >= 4.0:")
print(high_rated)

comedy_movies = movies_ratings[movies_ratings['genres'].str.contains('Comedy')]
print("\nComedy movies:")
print(comedy_movies)

avg_rating = movies_ratings.groupby('title')['rating'].mean().sort_values(ascending=False)
print("\nRating trung bình theo phim:")
print(avg_rating)

rating_count = movies_ratings.groupby('title')['rating'].count()
print("\nSố lượng rating mỗi phim:")
print(rating_count)

# 
movies_ratings['parsed_time'] = pd.to_datetime(movies_ratings['timestamp'], unit='s')
print("\n5 dòng đầu với parsed_time:")
print(movies_ratings[['userId','movieId','rating','parsed_time']].head())